


#  Configuration using config.yml
#
#  Use the config.yml file in the config directory to configure your system. If your desired camera is listed as source 0 you will configure video_source: 0. Alternatively you can configure the video source as an MJPEG or RTSP stream. For example in config.yml you may configure something like video_source: "rtsp://admin:password@192.168.1.94:554/11" for a commercial RTSP camera. To configure a RPi camera running the web_streaming.py example you configure video_source: http://pi_ip:8000/stream.mjpg
#
#  Validate the config can be loaded by running:
#
#    $ (venv) python3 scripts/validate-config.py
#
#    Note that this script does not check the accuracy of any of the values in config.yml, just that the file path is correct and the file structure is OK.
#
#    By default scripts/opencv-camera.py will look for the config file at ./config/config.yml but an alternative path can be specified using the environment variable MQTT_CAMERA_CONFIG


mqtt:
  broker: localhost # or an ip address like 192.168.1.164
  port: 1883
  QOS: 1

camera:
  video_source: 0 # http://192.168.1.134:8000/stream.mjpg for a picamera running web_server.py
  fps: 2
  mqtt_topic: homie/mac_webcam/capture

processing:
  subscribe_topic: homie/mac_webcam/capture
  publish_topic: homie/mac_webcam/capture/rotated

save-captures:
  mqtt_topic: homie/mac_webcam/capture
  captures_directory: captures/